### ISSUE TITLE
Update redis pipeline to pull pivotal-cf/shared-redis-release

### ISSUE THREAD

**Issue by 9numbernine9** [trecnoc/concourse-pipelines#41]

**Comment by mymasse** [comment]
Pipeline already exists

**Comment by mymasse** [comment]
Done in https://github.com/trecnoc/concourse-pipelines/commit/d217a2ad6ab23794a06e228215e05ed94f7d82fb#diff-a1a5f3845f35df9e5d451de807fefc43
